---
title: "MaPS-Seq_DeSeq2"
output: html_document
date: "2022-10-03"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

setwd("~/Dropbox/fmt/scripts/")
library(tidyverse)
library(wesanderson)
library(ggthemes)
library(data.table)
library(cowplot)
library("DESeq2")


ven <- c('#FAAF40',"#1B75BB","#37B34A", "#F05A28")
pal <- wes_palette("Zissou1", 100, type = "continuous")
samples <- c("Post FMT", "Pre FMT", "Donor")

options(stringsAsFactors = F)
options(scipen = 10000)

#zotu <- read_csv("../seq/zotu.csv") 
#tax <- read_csv("../seq/tax.csv")
meta <- read_csv("../experiments/2021-12-22_JvEPolysaccharideScreen/metadata/metadata.csv")
CorrectedData <- data.table::fread("~/Dropbox/fmt/experiments/2022-09-13 Guillaume FMT r3/CorrectedDataFrame.csv") %>% 
  separate(Sample, into = c('Sample', 'waste'), sep = 's', remove = T) %>% 
  filter(!(Sample %in% c('J1', 'J2', 'J3', 'J4', 'E5', 'E6', 'E7', 'E8', 'JE9', 'JE10', 'JE11', 'JE12'))) %>% select(-waste)

Tax_Table <- data.table::fread("~/Dropbox/fmt/experiments/2022-09-13 Guillaume FMT r3/SilvaTax.csv")


```

Make DeSeq dataframes

```{r}
#set <- samples[1]
  
#Prefilter data to remove OTUs with less than 10000 reads or Particles with less than 100 reads or > 100000
filtered_data <- CorrectedData %>% 
                    group_by(OTU) %>% 
                      mutate(num_OTU = sum(Count)) %>% ungroup() %>% 
                    group_by(Particle) %>%
                      mutate(num_particle = sum(Count)) %>% ungroup %>% 
                    filter(num_OTU > 100000 & num_particle > 100 & num_particle < 10000)

#Make count matrix
cts <- filtered_data %>% 
        select(Particle, Count, OTU) %>% 
        dcast(OTU~Particle, value.var = "Count") %>% 
        column_to_rownames("OTU")

#add pseudocounts
cts[is.na(cts)] <- 0
cts <-(cts + 1)

#Generate MetaData 
coldata <- cts %>% t() %>% as.data.frame %>% rownames_to_column("Particle") %>% select(Particle) %>%
           left_join(., select(filtered_data, Particle, Sample) %>% 
                  distinct) %>% 
       column_to_rownames("Particle") 

#Make sure dfs are correct
all(rownames(coldata) %in% colnames(cts))
all(rownames(coldata) == colnames(cts))

# fix names
coldata$Sample <- str_extract(coldata$Sample,"^[:alpha:]{1,2}")
coldata$Sample <- str_replace(coldata$Sample,"JE","Post FMT")
coldata$Sample <- str_replace(coldata$Sample,"J","Pre FMT")
coldata$Sample <- str_replace(coldata$Sample,"E","Donor")


```


```{r}

#Make DeSeq DataSet
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~ Sample)

#Differential 'expression' analysis
dds <- DESeq(dds)

#Build result table for pre FMT vs Post FMT
res_preFMT <- results(dds, contrast=c("Sample","Pre FMT","Post FMT"), 
                      pAdjustMethod = 'BH')

#Build result tabe for donor vs Post FMT
res_donor <- results(dds, contrast=c("Sample","Donor","Post FMT"), 
                     pAdjustMethod = 'BH')

```


Let's see those plots!!!
```{r}


## Obtain logical vector where TRUE values denote padj values < 0.05 and fold change > 2 in either direction
res_table_preFMT <- res_preFMT %>% as.data.frame() %>%
                  mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 1)
                  
## Volcano plot Pre FMT
ggplot(res_table_preFMT) +
    geom_point(aes(x = log2FoldChange, y = -log10(padj), colour = threshold)) +
    ggtitle("Pre FMT vs Post FMT") +
    xlab("log2 fold change") + 
    ylab("-log10 adjusted p-value") +
    #scale_y_log10() +
  ylim(0,1000) +
    theme_cowplot() +
    theme(legend.position = "none",
          plot.title = element_text(size = rel(1.5), hjust = 0.5),
          axis.title = element_text(size = rel(1.25)))          


#Donor
res_table_donor <- res_donor %>% as.data.frame() %>%
                  mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 1)

## Volcano plot Donor
ggplot(res_table_donor) +
    geom_point(aes(x = log2FoldChange, y = -log10(padj), colour = threshold)) +
    ggtitle("Donor vs Post FMT") +
    xlab("log2 fold change") + 
    ylab("-log10 adjusted p-value") +
    #scale_y_log10() +
    theme_cowplot() +
    theme(legend.position = "none",
          plot.title = element_text(size = rel(1.5), hjust = 0.5),
          axis.title = element_text(size = rel(1.25)))   

```

Assemble table of classifications
```{r}

#recipient specific
#Build result table to identify species enriched in pre FMT vs Donor then add on whether OTUs are enriched in postFMT to donor
compare <- results(dds, contrast=c("Sample","Donor","Pre FMT"), 
                      pAdjustMethod = 'BH') %>% as.data.frame() %>%
                      mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 1,
                             OTUType = ifelse(log2FoldChange > 0 & threshold == T, 
                                           "Donor Taxa", NA),
                             OTUType = ifelse(log2FoldChange < 0 & threshold == T,
                                           "Recipient Taxa", OTUType),
                             OTUType = ifelse(threshold == F, "Shared Taxa", OTUType)) %>%
                      rownames_to_column("OTU") %>% select(OTU, OTUType) %>%
 left_join(., results(dds, contrast=c("Sample","Post FMT","Pre FMT"), 
                      pAdjustMethod = 'BH') %>% as.data.frame() %>%
                      mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 1,
                             emergence = ifelse(log2FoldChange > 0 & threshold == T, 
                                           "enriched", NA),
                             emergence = ifelse(log2FoldChange < 0 & threshold == T,
                                           "depleted", emergence),
                             emergence = ifelse(threshold == F, "unchanged", emergence)) %>% 
                     rownames_to_column("OTU") %>% 
            select(OTU,baseMean, log2FoldChange, emergence)) %>% 
    #select(OTU, OTUType, baseMean emergence, log2FoldChange) %>%
   mutate(OTUcolor = ifelse(OTUType == 'Donor Taxa', 
                        paste("<b style='color:#377EB8'>", OTU, sep =''), #env specific
                    ifelse(OTUType == 'Recipient Taxa', 
                        paste("<b style='color:#E41A1C'>", OTU, sep =''), #jax specific
                        paste("<b style='color:#828382'>", OTU, sep =''))))


compare %>% select(OTUType) %>% group_by(OTUType) %>% mutate(num_type = n()) %>% distinct() 
compare %>% select(emergence) %>% group_by(emergence) %>% mutate(num_emergence = n()) %>% distinct() 


write.csv(compare, "../experiments/2022-09-13 Guillaume FMT r3/DeSeq_OTU_dynamics.csv", quote = F, row.names = F)


#temp <- inner_join((results(dds, contrast=c("Sample","Post FMT","Pre FMT"), 
#                      pAdjustMethod = 'BH') %>% as.data.frame() %>%
#                      mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 1)%>%
#                      filter(threshold == T) %>%
#                            rownames_to_column("OTU")),
#                   (results(dds, contrast=c("Sample","Post FMT","Donor"), 
#                      pAdjustMethod = 'BH') %>% as.data.frame() %>%
#                      mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 1)%>%
#                      filter(threshold == T) %>%
#                            rownames_to_column("OTU")))

```


Assemble table of classifications for donor vs post FMT
```{}

#recipient specific
#Build result table to identify species enriched in pre FMT vs Donor then add on whether OTUs are enriched in postFMT to donor
compare <- results(dds, contrast=c("Sample","Donor","Pre FMT"), 
                      pAdjustMethod = 'BH') %>% as.data.frame() %>%
                      mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 1,
                             OTUType = ifelse(log2FoldChange > 0 & threshold == T, 
                                           "Donor Taxa", NA),
                             OTUType = ifelse(log2FoldChange < 0 & threshold == T,
                                           "Recipient Taxa", OTUType),
                             OTUType = ifelse(threshold == F, "Shared Taxa", OTUType)) %>%
                      rownames_to_column("OTU") %>% select(-threshold) %>%
 left_join(., results(dds, contrast=c("Sample","Post FMT","donor"), 
                      pAdjustMethod = 'BH') %>% as.data.frame() %>%
                      mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 1,
                             emergence = ifelse(log2FoldChange > 0 & threshold == T, 
                                           "enriched", NA),
                             emergence = ifelse(log2FoldChange < 0 & threshold == T,
                                           "depleted", emergence),
                             emergence = ifelse(threshold == F, "unchanged", emergence)) %>% 
                     rownames_to_column("OTU") %>% select(emergence, OTU)) %>% 
    select(OTU, OTUType, emergence) %>%
   mutate(OTUcolor = ifelse(OTUType == 'Donor Taxa', 
                        paste("<b style='color:#377EB8'>", OTU, sep =''), #env specific
                    ifelse(OTUType == 'Recipient Taxa', 
                        paste("<b style='color:#E41A1C'>", OTU, sep =''), #jax specific
                        paste("<b style='color:#828382'>", OTU, sep =''))))


compare %>% select(OTUType) %>% group_by(OTUType) %>% mutate(num_type = n()) %>% distinct() 
compare %>% select(emergence) %>% group_by(emergence) %>% mutate(num_emergence = n()) %>% distinct() 

write.csv(compare, "../experiments/2022-09-13 Guillaume FMT r3/DeSeq_DonorVPost.csv", quote = F, row.names = F)



```