---
title: "20221216_Network_Species specific"
output: html_document
date: "2022-12-16"
---

```{r setup, include=FALSE}


```

#5E? Make network diagram of mean interactions, show all nodes in circle
```{r}

library(ggraph)
library(igraph)

bugColors <- setNames(c(scales::hue_pal()(length(unique(PrevalentSets$Class_OTU1)))), c(levels(as.factor(PrevalentSets$Class_OTU1))))

#average interactions 
mean_interactions <- PrevalentSets %>% group_by(MouseGroup, OTU1, OTU2) %>% 
  filter(zpadjusted < .01) %>% 
  mutate(average_corr = mean(Zscore),
         average_sig = mean(zpadjusted),
         interaction = ifelse(average_corr > 0, 'Positive', 'Negative')) %>% 
  select(OTU1, OTU2, average_corr, average_sig,interaction,MouseGroup, 
         Class_OTU1, Family_OTU1, Class_OTU2, Family_OTU2, OTU1Type, OTU2Type)%>% 
  distinct %>% ungroup()

#Count OTU instances
Instances <- rbind(PrevalentSets %>% select(MouseGroup, OTU1, Cluster, Instances=InstancesOTU1) %>% distinct(),
                   PrevalentSets %>% select(MouseGroup, OTU1=OTU2, Cluster, Instances=InstancesOTU2) %>% distinct()) %>% group_by(MouseGroup, OTU1) %>% mutate(total_instances = (sum(Instances))) %>% ungroup() %>% 
  select(OTU1, MouseGroup, total_instances) %>% distinct() %>% 
  mutate(OTU1 = gsub('Otu', '', .$OTU1))



#tbl_nodes[unique(tbl_nodes$Order_OTU1) %in% unique(PrevalentSet$Order_OTU1),]
#unique(tbl_nodes$Order_OTU1) %in% unique(PrevalentSet$Order_OTU1)


# Create data frame for edges

cluster_network <- mean_interactions %>% #left_join(., Instances, by = c("OTU1", "MouseGroup")) %>%
  left_join(., data.frame(OTU1Type = c("Donor Taxa", 'Recipient Taxa', 'Shared Taxa'), 
                            Color = c('#377Ebb', '#E41A1C','#828382'))) %>%
  mutate(OTU1 = gsub('Otu', '', .$OTU1),
         OTU2 = gsub('Otu', '', .$OTU2)) #only significant interactions




#Make dummy edges
tbl_edges_all <- cluster_network %>% 
  filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
    select(OTU1, OTU2, Class_OTU1,Class_OTU2) %>% 
    #mutate(interaction = 1) %>% 
    distinct()

edges <- rbind(select(tbl_edges_all,OTU1, Class_OTU1), select(tbl_edges_all, OTU1=OTU2, Class_OTU1=Class_OTU2)) %>% distinct()


#create node information
tbl_nodes_all <- cluster_network %>% 
  filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
  select(OTU1, Class_OTU1) %>%
  distinct() %>% left_join(edges,.) %>%   
  mutate(OTU1 = as.numeric(OTU1)) %>%
  arrange(OTU1) %>% mutate(OTU1 = as.character(OTU1)) %>% distinct()



# - FMT


#Now layer edges for -FMT
tbl_edges<- cluster_network %>% filter(MouseGroup == 'Pre FMT') %>%
    filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
      select(OTU1, OTU2, average_corr, average_sig) %>% 
    mutate(interaction = ifelse(average_corr > 0, 'Positive', 'Negative'),
           zpadjusted=log10(1/average_sig)) %>%
    select(OTU1, OTU2, interaction, average_corr) %>%
    #left_join(tbl_edges_all, ., by = c('OTU1','OTU2')) %>%
    replace(is.na(.), 0) %>%
    distinct()


#Get nodes found in -FMT

tbl_nodes <- rbind(cluster_network %>% filter(MouseGroup == 'Pre FMT') %>%
    filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
mutate(OTU1 = gsub('Otu', '', .$OTU1)) %>% select(OTU1)%>% distinct(),
    cluster_network %>% filter(MouseGroup == 'Pre FMT') %>%
    filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
   mutate(OTU2 = gsub('Otu', '', .$OTU2)) %>% select(OTU1=OTU2)%>% distinct()) %>% 
    mutate(alpha = 1) %>% distinct() %>% left_join(., filter(Instances, MouseGroup == 'Pre FMT'), by = 'OTU1') %>%
    select(-MouseGroup) %>% mutate(total_instances = as.numeric(total_instances)) %>%
  left_join(tbl_nodes_all, ., by = 'OTU1') %>% replace(is.na(.), .1) %>% distinct()




#merge node and edge data
graph_nodes <- graph_from_data_frame(tbl_edges, tbl_nodes, directed = T)

#graph just nodes
nodes <- ggraph(graph_nodes, layout = 'circle') +
   geom_edge_link(aes(
                      edge_width = abs(average_corr)*.001, 
                       alpha = abs(average_corr), 
                       edge_color = interaction),) +
      scale_edge_width(
                       aes((average_corr)),
                       range = c(.01, 2)
                       ) +
    scale_edge_color_manual(values = c('navyblue','firebrick')) +
  geom_node_point(aes(size = total_instances), color = 'black') +
  geom_node_point(aes( size = total_instances*.6, alpha = alpha), color = '#e58700') +
  labs(color = 'Order', 
         title = "Pre FMT") +
    theme(panel.background = element_blank(),
          legend.text = element_text(size = 12),
          plot.title = element_text(hjust = 0.5, size = 16),
          legend.key = element_blank(),
          legend.position = 'none') 

a <- nodes + geom_node_text(aes(label = name), size = 2.5,  nudge_x = nodes$data$x * .15, nudge_y = nodes$data$y * .15, check_overlap=FALSE)

# Donor

#Get nodes found in Donor



#Now layer edges for -FMT
tbl_edges<- cluster_network %>% filter(MouseGroup == 'Donor') %>%
    filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
      select(OTU1, OTU2, average_corr, average_sig) %>% 
    mutate(interaction = ifelse(average_corr > 0, 'Positive', 'Negative'),
           zpadjusted=log10(1/average_sig)) %>%
    select(OTU1, OTU2, interaction, average_corr) %>%
    #left_join(tbl_edges_all, ., by = c('OTU1','OTU2')) %>%
    replace(is.na(.), 0) %>%
    distinct()


#Get nodes found in -FMT

tbl_nodes <- rbind(cluster_network %>% filter(MouseGroup == 'Donor') %>%
    filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
mutate(OTU1 = gsub('Otu', '', .$OTU1)) %>% select(OTU1)%>% distinct(),
    cluster_network %>% filter(MouseGroup == 'Donor') %>%
    filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
   mutate(OTU2 = gsub('Otu', '', .$OTU2)) %>% select(OTU1=OTU2)%>% distinct()) %>% 
    mutate(alpha = 1) %>% distinct() %>% left_join(., filter(Instances, MouseGroup == 'Donor'), by = 'OTU1') %>%
    select(-MouseGroup) %>% mutate(total_instances = as.numeric(total_instances)) %>%
  left_join(tbl_nodes_all, ., by = 'OTU1') %>% replace(is.na(.), .1) %>% distinct()




#merge node and edge data
graph_nodes <- graph_from_data_frame(tbl_edges, tbl_nodes, directed = T)

#graph just nodes
nodes <- ggraph(graph_nodes, layout = 'circle') +
   geom_edge_link(aes(
                      edge_width = abs(average_corr)*.001, 
                       alpha = abs(average_corr), 
                       edge_color = interaction),) +
      scale_edge_width(
                       aes((average_corr)),
                       range = c(.01, 2)
                       ) +
    scale_edge_color_manual(values = c('navyblue','firebrick')) +
  geom_node_point(aes(size = total_instances), color = 'black') +
  geom_node_point(aes( size = total_instances*.6, alpha = alpha), color = '#e58700') +
  labs(color = 'Order', 
         title = "Donor") +
    theme(panel.background = element_blank(),
          legend.text = element_text(size = 12),
          plot.title = element_text(hjust = 0.5, size = 16),
          legend.key = element_blank(),
          legend.position = 'none') 

b <- nodes + geom_node_text(aes(label = name), size = 2.5,  nudge_x = nodes$data$x * .15, nudge_y = nodes$data$y * .15, check_overlap=FALSE)


# +FMT

#Now layer edges for +FMT
tbl_edges<- cluster_network %>% filter(MouseGroup == 'Post FMT') %>%
    filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
      select(OTU1, OTU2, average_corr, average_sig) %>% 
    mutate(interaction = ifelse(average_corr > 0, 'Positive', 'Negative'),
           zpadjusted=log10(1/average_sig)) %>%
    select(OTU1, OTU2, interaction, average_corr) %>%
    #left_join(tbl_edges_all, ., by = c('OTU1','OTU2')) %>%
    replace(is.na(.), 0) %>%
    distinct()


#Get nodes found in +FMT

tbl_nodes <- rbind(cluster_network %>% filter(MouseGroup == 'Post FMT') %>%
    filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
mutate(OTU1 = gsub('Otu', '', .$OTU1)) %>% select(OTU1)%>% distinct(),
    cluster_network %>% filter(MouseGroup == 'Post FMT') %>%
    filter(Class_OTU1 == 'Bacteroidales' & Class_OTU2 == 'Bacteroidales') %>%
   mutate(OTU2 = gsub('Otu', '', .$OTU2)) %>% select(OTU1=OTU2)%>% distinct()) %>% 
    mutate(alpha = 1) %>% distinct() %>% left_join(., filter(Instances, MouseGroup == 'Post FMT'), by = 'OTU1') %>%
    select(-MouseGroup) %>% mutate(total_instances = as.numeric(total_instances)) %>%
  left_join(tbl_nodes_all, ., by = 'OTU1') %>% replace(is.na(.), .1) %>% distinct()




#merge node and edge data
graph_nodes <- graph_from_data_frame(tbl_edges, tbl_nodes, directed = T)

#graph just nodes
nodes <- ggraph(graph_nodes, layout = 'circle') +
   geom_edge_link(aes(
                      edge_width = abs(average_corr)*.001, 
                       alpha = abs(average_corr), 
                       edge_color = interaction),) +
      scale_edge_width(
                       aes((average_corr)),
                       range = c(.01, 2)
                       ) +
    scale_edge_color_manual(values = c('navyblue','firebrick')) +
  geom_node_point(aes(size = total_instances), color = 'black') +
  geom_node_point(aes( size = total_instances*.6, alpha = alpha), color = '#e58700') +
  labs(color = 'Order', 
         title = "Post FMT") +
    theme(panel.background = element_blank(),
          legend.text = element_text(size = 12),
          plot.title = element_text(hjust = 0.5, size = 16),
          legend.key = element_blank(),
          legend.position = 'none') 


c <- nodes + geom_node_text(aes(label = name), size = 2.5,  nudge_x = nodes$data$x * .15, nudge_y = nodes$data$y * .15, check_overlap=FALSE)
c

leg <- cowplot::get_legend(ggraph(graph_nodes, layout = 'circle') + 
    geom_edge_link(aes(edge_width = average_corr), alpha =.4) +
    scale_edge_width_continuous(range = c(0,5)) +
    geom_node_point(size = 14, aes(color = Class_OTU1)) +
    scale_color_manual(values = bugColors) +labs(color = 'Order') +
      theme(panel.background = element_blank(),
          legend.text = element_text(size = 12),
          plot.title = element_text(hjust = 0.5, size = 16),
          legend.key = element_blank(),
          legend.position = 'bottom'))
    

temp <- cowplot::plot_grid(a,c, nrow = 1)
temp
ggsave("../figs/fig5/5E_InteractionNetworks.png", width = 5,height = 2.6)
ggsave("../figs/fig5/5E_InteractionNetworks.pdf", width = 5,height = 2.6)

#cowplot::plot_grid(leg)
#ggsave("../figs/fig5/5E_InteractionNetworks_leg.png", width = 14,height = 1.5)
#ggsave("../figs/fig5/5E_InteractionNetworks_leg.pdf", width = 14,height = 1.5)
#cowplot::plot_grid(temp, leg, nrow = 2)
```
