---
title: "BacteroidesVPolysaccharidePanel"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(pals)
library(tidyverse)
library(ggthemes)

rm(list=ls())

# Working directory for the experiment
#setwd("~/Dropbox/projects/fmt/experiments/2021-04-12_polysacc_growth_kinetics2/")
#setwd("~/Google_Drive/WangLab/Projects/FMT/2021April_FMTPolysaccharideScreen/2021-04-12_polysacc_growth_kinetics2/")
setwd("~/Desktop/WangLab_Research/Data_analysis/scripts/")
#knitr::opts_knit$set('~/Google_Drive/WangLab/Projects/FMT/2021April_FMTPolysaccharideScreen/2021-04-12_polysacc_growth_kinetics2/')
knitr::opts_knit$set("~/Desktop/WangLab_Research/Data_analysis/scripts/")

#  Load the metadata
meta <- read_csv("../metadata/metadata.csv")

# Load the tidy OD600 data processed w/ python script
data <- read_csv("../data/data.csv")
#  filter(well %in% meta$well) %>% # filter the data to those wells in the metadata
#  left_join(meta, by="well") # Add the metadata to each entry


# filter the data to those wells in the metadata
data <- data %>%
  filter(well %in% meta$well)

# Add the metadata to each entry
data <- data %>%
  left_join(meta, by="well")

# Define Order I want to plot polysaccharides in, to be used as levels (i.e. plot order)
#polysacc.order <-c("Water", "Arabinan", "Arabinogalactan", "A_Cellulose", "Cellulose",
#                   "Dextran", "Mucin", "Pectic Galactan", "Pectin", "MCF")
polysacc.order <-c("Water", "MGAM", "Glucose", "Dextran", "Inulin", "Cellobiose", "Mucin", "Arabino-galactan", "Pectin", "Amylopectin")

```


Normalize data
```{r}

# Compute the bg growth from the OD600 of the water wells
bg <- data %>%
  filter(polysacc == "Water") %>%
  group_by(time_mins) %>% #, sample_type, sample_dilution
  summarise(bg = mean(OD600))


# Add bg data to the actual data
# Remove water rows 
data <- data %>%
  left_join(bg, by=c("time_mins")) #, "sample_type", "sample_dilution"


# Compute OD600 normalized against water controls
data$norm_OD600 <- data$OD600 / data$bg

# Compute the OD600 corrected against water controls
data$corr_OD600 <- data$OD600 - data$bg

data

# convert sample type to factor which levels fixed in order I want to plot
#data$sample_type = factor(data$sample_type, levels = c("Bacteroides"))


# Order I want to plot polysacc in, to be used as levels
polysacc.order <-c("Water", "MGAM", "Glucose", "Dextran", "Inulin", "Cellobiose", "Mucin", "Arabinogalactan", "Pectin", "Amylopectin")

# convert polysacc to factor, levels in order I want to plot
#data$polysacc <- factor(data$polysacc, levels = polysacc.order)

#data$replicate <- factor(data$replicate, levels=as.character(unique(data$replicate)))


```

```{r}
# Plot raw data
raw.viz<- data  %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=OD600, color = sample)) + #changing color to fill (fill=replicate)
  #facet_grid(~polysacc) + 
  facet_wrap(~polysacc, nrow = 10, scales = "free") +
  xlab("Time (mins)") +
  xlim(0, 2880) + #limits the x axis in this case the runtime shown 
  labs(color="Replicate") +
  theme_clean() +
  theme(
    axis.title.x = element_text(size = 18),
    axis.text.x = element_text(size=16),
    axis.title.y = element_text(size = 18),
    axis.text.y = element_text(size=16),
    legend.title = element_text(size=18),
    legend.text = element_text(size=16),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

raw.viz
ggsave("../figures/raw_data_lineplot.svg", raw.viz)
ggsave("../figures/raw_data_lineplot.pdf", raw.viz, width=6, height=20)
  
```

```{r}
# Plot normalized data
#data$corr_OD600
#norm.viz <- data  %>%
corr.viz <- data  %>% 
  filter(polysacc != "Water", polysacc != "MGAM") %>% 
  group_by(polysacc) %>% mutate(Nmax = corr_OD600/max(corr_OD600)) %>%
  ungroup() %>% 
  ggplot() +
  geom_line(aes(x=time_mins, y=Nmax, color=sample)) +
  #facet_grid(~polysacc, nrow = 10) + 
  #facet_grid(polysacc~sample_type) + 
  facet_wrap(~polysacc, nrow = 10) + 
  xlab("Time (mins)") +
  xlim(0, 48*60) + 
  ylab("Normalized OD600") +
  labs(color="Sample") +
  ylim(-.2, 1) +
    theme_clean() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size=12),
    legend.title = element_text(size=14),
    legend.text = element_text(size=12),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

corr.viz
ggsave("../figures/corr_data_lineplot.svg", corr.viz)
ggsave("../figures/corr_data_lineplot.pdf", corr.viz, width=6, height=20)

```
```{r}
# Plot normalized data
#corr.viz <- data  %>%
#data$norm_OD600
norm.viz <- data  %>%
  filter(polysacc != "Water", polysacc != "MGAM") %>%
  group_by(polysacc) %>% mutate(Nmax = norm_OD600/max(norm_OD600)) %>%
  ungroup() %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=Nmax, color=sample)) +
  #facet_grid(polysacc~sample_type) + 
  facet_wrap(~polysacc, nrow = 10) + 
  xlab("Time (mins)") +
  xlim(0, 48*60) + 
  ylab("Correction OD600") +
  labs(color="Sample") +
  ylim(0, 1) +
    theme_clean() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size=12),
    legend.title = element_text(size=14),
    legend.text = element_text(size=12),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

norm.viz
ggsave("../figures/norm_data_lineplot.svg", norm.viz)
ggsave("../figures/norm_data_lineplot.pdf", norm.viz, width=8, height=10)
```

```{r}
#plot individual data 
# Arabinogalactan, Cellobiose, Glucose, Inulin, Pectin
## Arabinogalactan 

norm.viz <- data  %>%
  #filter(polysacc != "Water", polysacc != "MGAM", polysacc != "Glucose", polysacc != "Dextran", polysacc !="Inulin", polysacc != "Cellobiose", polysacc != "Mucin", polysacc != "Pectin", polysacc != "Amylopectin") %>%
  filter(polysacc == "Arabinogalactan") %>% 
  group_by(polysacc) %>% mutate(Nmax = norm_OD600/max(norm_OD600)) %>%
  ungroup() %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=Nmax, color=sample)) +
  #facet_grid(polysacc~sample_type) + 
  facet_wrap(~polysacc, nrow = 10) + 
  xlab("Time (mins)") +
  xlim(0, 48*60) + 
  ylab("Correction OD600") +
  labs(color="Sample") +
  ylim(0, 1) +
    theme_clean() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size=12),
    legend.title = element_text(size=14),
    legend.text = element_text(size=12),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

norm.viz
ggsave("../figures/Arabinogalactan_norm_data_lineplot.svg", norm.viz)
ggsave("../figures/Arabinogalactan_norm_data_lineplot.pdf", norm.viz, width=8, height=10)


```
```{r}
#plot individual data 
# Arabinogalactan, Cellobiose, Glucose, Inulin, Pectin
## Cellobiose 

norm.viz <- data  %>%
  filter(polysacc == "Cellobiose") %>%
  group_by(polysacc) %>% mutate(Nmax = norm_OD600/max(norm_OD600)) %>%
  ungroup() %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=Nmax, color=sample)) +
  #facet_grid(polysacc~sample_type) + 
  facet_wrap(~polysacc, nrow = 10) + 
  xlab("Time (mins)") +
  xlim(0, 48*60) + 
  ylab("Correction OD600") +
  labs(color="Sample") +
  ylim(0, 1) +
    theme_clean() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size=12),
    legend.title = element_text(size=14),
    legend.text = element_text(size=12),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

norm.viz
ggsave("../figures/Cellobiose_norm_data_lineplot.svg", norm.viz)
ggsave("../figures/Cellobiose_norm_data_lineplot.pdf", norm.viz, width=8, height=10)


```

```{r}
#plot individual data 
# Arabinogalactan, Cellobiose, Glucose, Inulin, Pectin
## Glucose 

norm.viz <- data  %>%
  filter(polysacc != "Water", polysacc != "MGAM", polysacc != "Arabinogalactan", polysacc != "Dextran", polysacc !="Inulin", polysacc != "Cellobiose", polysacc != "Mucin", polysacc != "Pectin", polysacc != "Amylopectin") %>%
  group_by(polysacc) %>% mutate(Nmax = norm_OD600/max(norm_OD600)) %>%
  ungroup() %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=Nmax, color=sample)) +
  #facet_grid(polysacc~sample_type) + 
  facet_wrap(~polysacc, nrow = 10) + 
  xlab("Time (mins)") +
  xlim(0, 48*60) + 
  ylab("Correction OD600") +
  labs(color="Sample") +
  ylim(0, 1) +
    theme_clean() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size=12),
    legend.title = element_text(size=14),
    legend.text = element_text(size=12),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

norm.viz
ggsave("../figures/Glucose_norm_data_lineplot.svg", norm.viz)
ggsave("../figures/Glucose_norm_data_lineplot.pdf", norm.viz, width=8, height=10)


```

```{r}
#plot individual data 
# Arabinogalactan, Cellobiose, Glucose, Inulin, Pectin
## Inulin 

norm.viz <- data  %>%
  filter(polysacc == "Inulin") %>%
  group_by(polysacc) %>% mutate(Nmax = norm_OD600/max(norm_OD600)) %>%
  ungroup() %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=Nmax, color=sample)) +
  #facet_grid(polysacc~sample_type) + 
  facet_wrap(~polysacc, nrow = 10) + 
  xlab("Time (mins)") +
  xlim(0, 48*60) + 
  ylab("Correction OD600") +
  labs(color="Sample") +
  ylim(0, 1) +
    theme_clean() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size=12),
    legend.title = element_text(size=14),
    legend.text = element_text(size=12),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

norm.viz
ggsave("../figures/Inulin_norm_data_lineplot.svg", norm.viz)
ggsave("../figures/Inulin_norm_data_lineplot.pdf", norm.viz, width=8, height=10)


```

```{r}
#plot individual data 
# Arabinogalactan, Cellobiose, Glucose, Inulin, Pectin
## Pectin 

norm.viz <- data  %>%
  filter(polysacc != "Water", polysacc != "MGAM", polysacc != "Glucose", polysacc != "Dextran", polysacc !="Inulin", polysacc != "Cellobiose", polysacc != "Mucin", polysacc != "Arabinogalactan", polysacc != "Amylopectin") %>%
  #filter(polysacc == "Pectin") %>% 
  group_by(polysacc) %>% mutate(Nmax = norm_OD600/max(norm_OD600)) %>%
  ungroup() %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=Nmax, color=sample)) +
  #facet_grid(polysacc~sample_type) + 
  facet_wrap(~polysacc, nrow = 10) + 
  xlab("Time (mins)") +
  xlim(0, 48*60) + 
  ylab("Correction OD600") +
  labs(color="Sample") +
  ylim(0, 1) +
    theme_clean() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size=12),
    legend.title = element_text(size=14),
    legend.text = element_text(size=12),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

norm.viz
ggsave("../figures/Pectin_norm_data_lineplot.svg", norm.viz)
ggsave("../figures/Pectin_norm_data_lineplot.pdf", norm.viz, width=8, height=10)


```

```{r}
#plot individual data 
# Arabinogalactan, Cellobiose, Glucose, Inulin, Pectin
## Pectin 

#norm.viz <- data  %>%
norm+corr.viz <- data %>%
  filter(polysacc != "Water", polysacc != "MGAM", polysacc != "Glucose", polysacc != "Dextran", polysacc !="Inulin", polysacc != "Cellobiose", polysacc != "Mucin", polysacc != "Arabinogalactan", polysacc != "Amylopectin") %>%
  group_by(polysacc) %>% mutate(Nmax = norm_OD600/max(norm_OD600)) %>%
  ungroup() %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=Nmax, color=sample)) +
  #facet_grid(polysacc~sample_type) + 
  facet_wrap(~polysacc, nrow = 10) + 
  xlab("Time (mins)") +
  xlim(0, 48*60) + 
  ylab("Correction OD600") +
  labs(color="Sample") +
  ylim(0, 1) +
    theme_clean() +
  theme(
    axis.title.x = element_text(size = 14),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size=12),
    legend.title = element_text(size=14),
    legend.text = element_text(size=12),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

norm.viz
ggsave("../figures/Pectin_norm_data_lineplot.svg", norm.viz)
ggsave("../figures/Pectin_norm_data_lineplot.pdf", norm.viz, width=8, height=10)


```

```{r}
# Create averaged out data
avg.data <- data %>%
  group_by(polysacc, sample_type, time_mins) %>%
  summarise(OD600 = mean(OD600), bg= mean(bg))

# Compute OD600 normalized against water controls
avg.data$norm_OD600 <- avg.data$OD600 / avg.data$bg

# Compute the OD600 corrected against water controls
avg.data$corr_OD600 <- avg.data$OD600 - avg.data$bg
  

# Plot averaged out data
avg.viz <- avg.data  %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=OD600, color=polysacc)) +
  facet_grid(polysacc~sample_type) +
  xlab("Time (mins)") +
  labs(color="Replicate") +
  theme(
    axis.title.x = element_text(size = 18),
    axis.text.x = element_text(size=16),
    axis.title.y = element_text(size = 18),
    axis.text.y = element_text(size=16),
    legend.title = element_text(size=18),
    legend.text = element_text(size=16),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

avg.viz
ggsave("../figures/avg_data_lineplot.svg", avg.viz)
ggsave("../figures/avg_data_lineplot.pdf", avg.viz, width=8, height=10)

```
```{r}



``` 

```{r}

# plot out averaged normalized data
# Plot normalized data
avg.norm.viz <- avg.data  %>%
  filter(polysacc != "Water") %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=norm_OD600, color=polysacc)) +
  facet_grid(polysacc~sample_type) + 
  xlab("Time (mins)") +
  ylab("Normalized OD600") +
  labs(color="Replicate") +
  ylim(0, 4) + 
  theme(
    axis.title.x = element_text(size = 14),
    axis.text.x = element_text(size=12),
    axis.title.y = element_text(size = 14),
    axis.text.y = element_text(size=12),
    legend.title = element_text(size=14),
    legend.text = element_text(size=12),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

avg.norm.viz
ggsave("../figures/norm_data_lineplot.svg", avg.norm.viz)
ggsave("../figures/norm_data_lineplot.pdf", avg.norm.viz, width=8, height=10)

```

```{r}
avg.data

# Plot out avg data w/ Jax vs. Envigo together
grouped.avg.viz <- avg.data  %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=OD600, color=sample_type)) +
  facet_grid(polysacc~.) +
  xlab("Time (mins)") +
  labs(color="Mouse Type") +
      theme_clean() +
  theme(
    axis.title.x = element_text(size = 18),
    axis.text.x = element_text(size=16),
    axis.title.y = element_text(size = 18),
    axis.text.y = element_text(size=16),
    legend.title = element_text(size=18),
    legend.text = element_text(size=16),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

grouped.avg.viz
ggsave("../figures/grouped_avg_data_lineplot_splitCond.svg", grouped.avg.viz)
ggsave("../figures/grouped_avg_data_lineplot_splitCond.pdf", grouped.avg.viz, width=8, height=10)


```

Plot Normalized average of jax with envigo
```{r}
norm_grouped.avg.viz <- avg.data  %>%
    filter(polysacc != "Water") %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=norm_OD600, color=sample_type)) +
  facet_grid(polysacc~., scales = 'free_y') +
  xlab("Time (mins)") +
  labs(color="Mouse Type") +
      theme_clean() +
  theme(
    axis.title.x = element_text(size = 18),
    axis.text.x = element_text(size=16),
    axis.title.y = element_text(size = 18),
    axis.text.y = element_text(size=16),
    legend.title = element_text(size=18),
    legend.text = element_text(size=16),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

norm_grouped.avg.viz
ggsave("../figures/norm_grouped_avg_data_lineplot_splitCond.svg", grouped.avg.viz)
ggsave("../figures/norm_grouped_avg_data_lineplot_splitCond.pdf", grouped.avg.viz, width=8, height=10)



```

```{r}

#Plot all 
allconditions.avg.viz <- avg.data  %>%
  ggplot() +
  geom_line(aes(x=time_mins, y=OD600, color=polysacc)) +
  facet_grid(sample_type~.) +
  xlab("Time (mins)") +
  labs(color="Mouse Type") +
      theme_clean() +
  theme(
    axis.title.x = element_text(size = 18),
    axis.text.x = element_text(size=16),
    axis.title.y = element_text(size = 18),
    axis.text.y = element_text(size=16),
    legend.title = element_text(size=18),
    legend.text = element_text(size=16),
    strip.text.x = element_text(size=12),
    strip.text.y = element_text(size=12),
    strip.text.y.right = element_text(angle = 0))

allconditions.avg.viz
ggsave("../figures/grouped_avg_data_lineplot.svg", allconditions.avg.viz)
ggsave("../figures/grouped_avg_data_lineplot.pdf", allconditions.avg.viz, width=8, height=10)


```