---
title: "MaPS-Seq_DeSeq2"
output: html_document
date: "2022-10-03"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

setwd("~/Dropbox/fmt/scripts/")
library(tidyverse)
library(wesanderson)
library(ggthemes)
library(data.table)
library(cowplot)
library("DESeq2")


ven <- c('#FAAF40',"#1B75BB","#37B34A", "#F05A28")
pal <- wes_palette("Zissou1", 100, type = "continuous")
samples <- c("J", "E", "JEJ", "JEE")

options(stringsAsFactors = F)
options(scipen = 10000)
#Redo
CorrectedData <- data.table::fread("~/Dropbox/fmt/experiments/20230516_FMT_MaPS-Seq2/20230823_MaPSFMT_redo_ProcessingScripts/ProcessedResults/CorrectedDataFrame.csv") %>% 
                separate(col = Sample,     #split into column
                       into = c('date', 'MouseGroup', 'Mouse_num', 'replicate'),
                       sep = '-', remove = F) %>% 
                select(-date)  #remove unnecessary date file
  

Tax_Table <- data.table::fread("~/Dropbox/fmt/experiments/20230516_FMT_MaPS-Seq2/20230823_MaPSFMT_redo_ProcessingScripts/ProcessedResults/tax.csv") %>% select(-ends_with('conf'))


```

Subset OTUs over .1% in J or E
```{r}

temp <- CorrectedData %>% filter(MouseGroup == 'J' | MouseGroup == 'E') %>% 
  select(OTU, Count, MouseGroup) %>% 
  group_by(OTU, MouseGroup) %>% mutate(OTU_Count = sum(Count)) %>% 
  ungroup %>% select(-Count) %>% distinct() %>%
  group_by(MouseGroup) %>% mutate(OTU_relabd = (OTU_Count/sum(OTU_Count))*100) %>% 
  filter(OTU_relabd > .1) %>% select(OTU) %>% distinct()

print(paste('# OTUs in J:', nrow(filter(temp, MouseGroup == 'J'))))
print(paste('# OTUs in E:',nrow(filter(temp, MouseGroup == 'E'))))

otus.to.keep <- unique(temp$OTU)

```
Make DeSeq dataframes

```{r}
#set <- samples[1]
  
#Prefilter data to remove OTUs with less than 50000 reads or Particles with less than 100 reads or > 100000
filtered_data <- CorrectedData %>% 
          filter(OTU %in% otus.to.keep) %>% filter(Count > 1) %>%
                    group_by(OTU) %>% 
                      mutate(num_OTU = sum(Count)) %>% ungroup() %>% 
                    group_by(Particle) %>%
                      mutate(num_particle = sum(Count)) %>% ungroup %>% 
                    filter(num_OTU > 50000 & num_particle > 100 & num_particle < 10000)

#Using same filtering as maps-seq
# filtered_data <- CorrectedData %>% 
#     filter(OTU %in% otus.to.keep) %>%
#   group_by(Particle) %>% 
#           mutate(total_particle_reads = sum(Count),
#                  OTU_rel_abd = Count/sum(Count))  %>% 
#                                                 ungroup() %>%
#                                                 filter(OTU_rel_abd > .01) %>% 
#                                                 group_by(Particle) %>% 
#                                                 mutate(num_OTUs_particle = n()) %>% 
#                                                 ungroup %>% group_by(Sample) %>% 
#                                                 mutate(ParticleNumberPerSample = n()) %>%
#                                                 ungroup() %>%
#                                                 filter(
#                                                        num_OTUs_particle > 1,
#                                                        total_particle_reads > 100, #changed from 100
#                                                        total_particle_reads < 10000
#                                                 ) %>%
#                                                 ungroup() 

#Make count matrix
cts <- filtered_data %>% 
        select(Particle, Count, OTU) %>% 
        reshape2::dcast(OTU~Particle, value.var = "Count") %>% 
        column_to_rownames("OTU")

#add pseudocounts
cts[is.na(cts)] <- 0
cts <-(cts + 1)

#Generate MetaData 
coldata <- cts %>% t() %>% as.data.frame %>% rownames_to_column("Particle") %>% 
           select(Particle) %>%
           left_join(., select(filtered_data, Particle, Sample, MouseGroup) %>% 
                  distinct) %>% 
            column_to_rownames("Particle") %>% mutate(MouseGroup = as.factor(MouseGroup))

#Make sure dfs are correct
all(rownames(coldata) %in% colnames(cts))
all(rownames(coldata) == colnames(cts))



```


```{r}

#Make DeSeq DataSet
dds <- DESeqDataSetFromMatrix(countData = cts,
                              colData = coldata,
                              design = ~MouseGroup)

#Differential 'expression' analysis
set.seed(123)
dds <- DESeq(dds)

#Build result table for pre FMT vs Post FMT
res_preFMT <- results(dds, contrast=c("MouseGroup","J","JEJ"), 
                      pAdjustMethod = 'BH')

#Build result tabe for donor vs Post FMT
res_donor <- results(dds, contrast=c("MouseGroup","E","JEJ"), 
                     pAdjustMethod = 'BH')

```


Let's see those plots!!!
```{r}


## Obtain logical vector where TRUE values denote padj values < 0.05 and fold change > 2 in either direction
res_table_preFMT <- res_preFMT %>% as.data.frame() %>%
                  mutate(threshold = padj < 0.01 & abs(log2FoldChange) >= 1)
                  
## Volcano plot Pre FMT
ggplot(res_table_preFMT) +
    geom_point(aes(x = log2FoldChange, y = -log10(padj), colour = threshold)) +
    ggtitle("Pre FMT vs Post FMT") +
    xlab("log2 fold change") + 
    ylab("-log10 adjusted p-value") +
    #scale_y_log10() +
  ylim(0,1000) +
    theme_cowplot() +
    theme(legend.position = "none",
          plot.title = element_text(size = rel(1.5), hjust = 0.5),
          axis.title = element_text(size = rel(1.25)))          


#Donor
res_table_donor <- res_donor %>% as.data.frame() %>%
                  mutate(threshold = padj < 0.01 & abs(log2FoldChange) >= 1)

## Volcano plot Donor
ggplot(res_table_donor) +
    geom_point(aes(x = log2FoldChange, y = -log10(padj), colour = threshold)) +
    ggtitle("Donor vs Post FMT") +
    xlab("log2 fold change") + 
    ylab("-log10 adjusted p-value") +
    #scale_y_log10() +
    theme_cowplot() +
    theme(legend.position = "none",
          plot.title = element_text(size = rel(1.5), hjust = 0.5),
          axis.title = element_text(size = rel(1.25)))   

```

Assemble table of classifications
```{r}

#recipient specific
#Build result table to identify species enriched in pre FMT vs Donor then add on whether OTUs are enriched in postFMT to donor
compare <- results(dds, contrast=c("MouseGroup","E","J"), 
                      pAdjustMethod = 'BH') %>% as.data.frame() %>%
                      mutate(threshold = padj < 0.01 & abs(log2FoldChange) >= 1,
                             OTUType = ifelse(log2FoldChange > 0 & threshold == T, 
                                           "Donor Taxa", NA),
                             OTUType = ifelse(log2FoldChange < 0 & threshold == T,
                                           "Recipient Taxa", OTUType),
                             OTUType = ifelse(threshold == F, "Shared Taxa", OTUType)) %>%
                      rownames_to_column("OTU") %>% select(OTU, OTUType) %>%
 left_join(., results(dds, contrast=c("MouseGroup","JEJ","J"), 
                      pAdjustMethod = 'BH') %>% as.data.frame() %>%
                      mutate(threshold = padj < 0.01 & abs(log2FoldChange) >= 1,
                             emergence = ifelse(log2FoldChange > 0 & threshold == T, 
                                           "enriched", NA),
                             emergence = ifelse(log2FoldChange < 0 & threshold == T,
                                           "depleted", emergence),
                             emergence = ifelse(threshold == F, "unchanged", emergence)) %>% 
                     rownames_to_column("OTU") %>% 
            select(OTU,baseMean, log2FoldChange, emergence)) %>%
    #select(OTU, OTUType, baseMean emergence, log2FoldChange) %>%
   mutate(OTUcolor = ifelse(OTUType == 'Donor Taxa', 
                        paste("<b style='color:#377EB8'>", OTU, sep =''), #env specific
                    ifelse(OTUType == 'Recipient Taxa', 
                        paste("<b style='color:#E41A1C'>", OTU, sep =''), #jax specific
                        paste("<b style='color:#828382'>", OTU, sep =''))))



compare %>% select(OTUType) %>% group_by(OTUType) %>% mutate(num_type = n()) %>% distinct() 
compare %>% select(emergence) %>% group_by(emergence) %>% mutate(num_emergence = n()) %>% distinct() 


write.csv(compare, "../experiments/20230516_FMT_MaPS-Seq2/processed_data/DeSeq_OTU_dynamics.csv", quote = F, row.names = F)


```


